{{- if .Values.features.uaa.native }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: uaa
  labels:
    {{- list . "uaa" | include "kubecf.component.labels" | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
