{{- if .Values.features.uaa.native }}
---
apiVersion: v1
kind: Service
metadata:
  name: uaa-native
  namespace: {{ .Release.Namespace }}
  labels:
    {{- list . "uaa" | include "kubecf.component.labels" | nindent 4 }}
spec:
  clusterIP: None
  ports:
  - name: http-uaa
    port: 8080
    protocol: TCP
    targetPort: http-uaa
  - name: ssl-uaa
    port: 8443
    protocol: TCP
    targetPort: ssl-uaa
  selector:
    {{- list . "uaa" | include "kubecf.component.selector" | nindent 4 }}
  type: ClusterIP
{{- end }}
