name: Pull Request Tests
on:
  # Trigger the workflow when PRs are labeled
  pull_request:
    branches: [master]
    types: [labeled]
  workflow_dispatch: {}

env:
  GIT_PAGER: cat

jobs:

  # The first thing we do is to check that the PR has the pr-test-trigger label
  # If it doesn't have it, the flow stops. If it does, we remove it (approval is good for one run only).
  dequeue:
    name: Dequeue
    if: >
      github.event_name == 'workflow_dispatch'
      || contains(github.event.pull_request.labels.*.name, 'pr-test-trigger')
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-ecosystem/action-remove-labels@556e306
        with:
          github_token: ${{ secrets.github_token }}
          labels: pr-test-trigger
        if: github.event_name == 'pull_request'

  build:
    name: Build
    runs-on: ubuntu-20.04
    needs: dequeue
    env:
      PINNED_TOOLS: true
      TOOLS_DIR: ${{ github.workspace }}/tools
    defaults:
      run:
        working-directory: kubecf

    strategy:
      matrix:
        include:
          - name: kubecf-bundle.tgz
            version: ""
          - name: kubecf-bundle-next.tgz
            version: "99.0.0"
      fail-fast: true

    steps:
      # Checkout kubecf
      - name: Checkout KubeCF
        uses: actions/checkout@v2
        with:
          path: kubecf
          fetch-depth: 0
          submodules: recursive
          persist-credentials: false

      # Python setup
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Caching tools like helm, jq, git, y2j, yamllint etc
      - name: cache.tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools

      # Install tools
      - run: make tools-install

      # Generate kubecf bundle
      - run: make kubecf-bundle
        env:
          VERSION: ${{ matrix.version }}
          TARGET_FILE: ${{ github.workspace }}/${{ matrix.name }}

      # Extract tgz of kubecf bundle
      - run: |
          mkdir bundle
          tar xf ${{ matrix.name }} -C bundle
        working-directory: ${{ github.workspace }}

      # Upload generated tgz bundle
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.name }}
          path: ${{ github.workspace }}/bundle

  tests:
    name: Tests
    runs-on: ubuntu-20.04
    needs: build
    env:
      # For KubeCF
      PINNED_TOOLS: true
      TOOLS_DIR: ${{ github.workspace }}/tools
      FEATURE_AUTOSCALER: "true"
      # For catapult
      # Note that credentials-related parts are in the individual steps
      BACKEND: gke
      DOWNLOAD_CATAPULT_DEPS: "false"
      CLUSTER_NAME: ci-${{ github.run_id }}-${{ matrix.backend }}-${{ matrix.upgrade }}
    defaults:
      run:
        working-directory: kubecf

    # Matrix to test diego and eirini
    strategy:
      matrix:
        upgrade: [ "no-upgrade", "upgrade" ]
        include:
          - backend: diego
            internetless: true
            ccdb-rotate: true
          - backend: eirini
            internetless: false
            ccdb-rotate: false
      fail-fast: false

    steps:
      # Checkout kubecf
      - name: Checkout KubeCF
        uses: actions/checkout@v2
        with:
          path: kubecf
          submodules: recursive
          persist-credentials: false
        timeout-minutes: 1

      # We need catapult to create Kubernetes clusters
      - name: Checkout catapult
        uses: actions/checkout@v2
        with:
          repository: SUSE/catapult
          path: catapult
          persist-credentials: false
        timeout-minutes: 1

      # Python setup
      - uses: actions/setup-python@v2
        with:
          # Force 3.8 because google-cloud-sdk is incompatible with 3.9
          # https://issuetracker.google.com/issues/170125513
          python-version: '3.8'
        timeout-minutes: 1

      # Caching tools like helm, jq, git, y2j, yamllint etc
      - name: cache.tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/tools
          key: ${{ runner.os }}-tools
        timeout-minutes: 5

      # Install tools
      - run: make tools-install
        timeout-minutes: 1 # this should take ~ 20 seconds

      # Add tools to path
      - name: Add tools to path
        run: echo "${{ github.workspace }}/kubecf/output/bin" >> "${GITHUB_PATH}"
        timeout-minutes: 1

      - name: Download Previous Release Bundle
        if: matrix.upgrade == 'upgrade'
        id: download-bundle-previous
        uses: XAMPPRocky/get-github-release@c28f4f6f4c0e5ce19f89ee5819d5472cd782da46
        with:
          # Delibrately not getting releases from forks
          owner: cloudfoundry-incubator
          repo: kubecf
          matches: "kubecf-bundle-.*.tgz"
          token: ${{ github.token }}
          install_path: "${GITHUB_WORKSPACE}"
        timeout-minutes: 2

      - name: Extract Previous Release Bundle
        if: matrix.upgrade == 'upgrade'
        run: |
          mkdir "${GITHUB_WORKSPACE}/kubecf-bundle-previous"
          tar xf "${ARCHIVE}" -C "${GITHUB_WORKSPACE}/kubecf-bundle-previous"
        env:
          ARCHIVE: ${{ steps.download-bundle-previous.outputs.install_path }}

      # Download chart bundle
      - id: download-bundle
        name: Download chart bundle
        uses: actions/download-artifact@v2
        with:
          name: kubecf-bundle.tgz
          # The artifact upload/download creates an extra directory
          path: ${{ github.workspace }}/kubecf-bundle
        timeout-minutes: 1

      - name: Download Future Chart Bundle
        if: matrix.upgrade == 'upgrade'
        id: download-next-bundle
        uses: actions/download-artifact@v2
        with:
          name: kubecf-bundle-next.tgz
          # The artifact upload/download creates an extra directory
          path: ${{ github.workspace }}/kubecf-bundle-next
        timeout-minutes: 1

      # Start SSH agent for catapult
      - name: Start SSH agent
        if: env.BACKEND == 'aks'
        run: |
          set -o errexit -o pipefail -o nounset
          eval "$(ssh-agent -s)"
          ssh-keygen -t rsa -b 4096 -N '' -C "KubeCF CI #${{ github.run_id }}" -f ssh-key
          ssh-add ssh-key
          echo "::add-mask::$(cat ssh-key.pub)"
          rm -f ssh-key ssh-key.pub
          echo "SSH_AUTH_SOCK=${SSH_AUTH_SOCK}" >> "${GITHUB_ENV}"
          echo "SSH_AGENT_PID=${SSH_AGENT_PID}" >> "${GITHUB_ENV}"
        timeout-minutes: 1

      # set GKE secret. TBD: use vault instead
      - name: set GKE_CRED_JSON
        if: env.BACKEND == 'gke'
        run: |
          json_file="$(mktemp)"
          echo "$GKE_CRED_JSON" > "${json_file}"
          echo "GKE_CRED_JSON=${json_file}" >> "${GITHUB_ENV}"
        env:
          GKE_CRED_JSON: ${{ secrets.GKE_CRED_JSON }}
        timeout-minutes: 1

      # Cache catapult's common tools
      - name: cache.catapult-common-tools
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/catapult/modules/common/bin
          key: ${{ runner.os }}-catapult-common-tools
        timeout-minutes: 1

      # Deploy k8s cluster
      - run: make k8s
        working-directory: catapult
        env:
          GKE_CLUSTER_NAME: kubecf-ci-${{ github.run_id }}-${{ matrix.backend }}
          OWNER: ${{ github.repository_owner }}
          DEBUG_MODE: true
          GKE_NODE_COUNT: 1
          GKE_PREEMPTIBLE: false
          GKE_INSTANCE_TYPE: n2d-standard-8
          EXTRA_LABELS: '{"ci": "${{ github.run_id }}"}'
        timeout-minutes: 20 # This should take ~10 minutes.

      - name: Set Up GKE Configuration Directory
        if: env.BACKEND == 'gke'
        working-directory: catapult/build${{ env.CLUSTER_NAME }}
        run: |
          . .envrc
          echo "CLOUDSDK_CONFIG=${CLOUDSDK_CONFIG}" >> "${GITHUB_ENV}"
        timeout-minutes: 1

      # Providing kubeconfig for debugging
      - name: export KUBECONFIG
        run: |
          set -o errexit -o nounset -o pipefail
          source .envrc
          echo "KUBECONFIG=${KUBECONFIG}" >> "${GITHUB_ENV}"
          # Debugging aid; should be safe as the cluster will be torn down
          # at the end of the run.
          kubectl config view --minify --flatten | gzip | base64 --wrap=0
        working-directory: catapult/build${{ env.CLUSTER_NAME }}
        timeout-minutes: 1

      # TBD: Don't generate values.yaml
      - name: Generate KubeCF Configuration
        run: exec "${GITHUB_WORKSPACE}/kubecf/.github/workflows/pull-request-ci/kubecf-gen-config.sh"
        env:
          AUTOSCALER: "true"
          ENABLE_EIRINI: ${{ matrix.backend == 'eirini' }}
        timeout-minutes: 1

      - name: Install Previous Operator
        if: matrix.upgrade == 'upgrade'
        run: make cf-operator-apply
        env:
          CHART: "${{ github.workspace }}/kubecf-bundle-previous/cf-operator.tgz"
        timeout-minutes: 1 # This should take ~10 seconds.

      - name: Wait for Operator to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make cf-operator-wait
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Install Previous KubeCF
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-apply
        env:
          CHART: ${{ github.workspace }}/kubecf-bundle-previous/kubecf_release.tgz
          FEATURE_EIRINI: ${{ matrix.backend == 'eirini' }}
          VALUES: ${{ github.workspace }}/kubecf-values.yaml
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Wait for Previous KubeCF to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-wait
        timeout-minutes: 30 # This should take ~15 minutes.

      - name: List Releases (Previous KubeCF)
        if: matrix.upgrade == 'upgrade'
        run: helm ls --all-namespaces
        timeout-minutes: 1 # This should take ~20 seconds.

      - name: Run Smoke Tests (Previous KubeCF)
        if: matrix.upgrade == 'upgrade'
        run: make smoke-tests
        timeout-minutes: 10

      - name: Install / Upgrade Operator
        run: make cf-operator-apply
        env:
          CHART: ${{ github.workspace }}/kubecf-bundle/cf-operator.tgz
        timeout-minutes: 1 # This should take ~10 seconds.

      - name: Wait for Operator to be Ready
        run: make cf-operator-wait
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Wait for KubeCF to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-wait
        timeout-minutes: 2 # This should take ~20 seconds.

      - name: Install KubeCF
        run: make kubecf-apply
        env:
          CHART: ${{ github.workspace }}/kubecf-bundle/kubecf_release.tgz
          FEATURE_EIRINI: ${{ matrix.backend == 'eirini' }}
          VALUES: ${{ github.workspace }}/kubecf-values.yaml
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Wait for KubeCF to be Ready
        run: make kubecf-wait
        timeout-minutes: 30 # This should take ~15 minutes.

      - name: List Helm Releases
        run: helm ls --all-namespaces
        timeout-minutes: 1 # This should take ~20 seconds.

      - name: Run Smoke Tests
        run: make smoke-tests
        timeout-minutes: 10

      - name: Run Brain Tests
        if: matrix.upgrade != 'upgrade'
        run: make brain-tests
        timeout-minutes: 25

      - name: Run Sync Integration Tests
        run: make sync-integration-tests
        if: (matrix.upgrade != 'upgrade') && (matrix.backend == 'diego')
        timeout-minutes: 5

      - name: Run Cloud Foundry Acceptance Tests
        if: matrix.upgrade != 'upgrade'
        run: make acceptance-tests
        timeout-minutes: 180

      - name: Set Up Network Isolation
        if: matrix.upgrade != 'upgrade'
        id: internetless-cats-isolate
        run: >
          exec
          "${GITHUB_WORKSPACE}/kubecf/.github/workflows/pull-request-ci/isolate-network.sh"
          --enable
        continue-on-error: ${{ !matrix.internetless }}
        timeout-minutes: 1

      - name: Override CATS Configuration
        id: internetless-cats-config
        if: steps.internetless-cats-isolate.outcome == 'success'
        run: >
          exec
          "${GITHUB_WORKSPACE}/kubecf/.github/workflows/pull-request-ci/override-cats-properties.sh"
          <<< '
            { acceptance_tests:
              { include: "=internetless", credhub_mode: skip-tests }
            }'
        continue-on-error: ${{ !matrix.internetless }}
        timeout-minutes: 1

      - name: Internetless Acceptance Tests
        run: make acceptance-tests
        if: steps.internetless-cats-config.outcome == 'success'
        continue-on-error: ${{ !matrix.internetless }}
        timeout-minutes: 10

      - name: Tear Down Network Isolation
        if: always() && steps.internetless-cats-isolate.outcome != 'skipped'
        run: >
          exec
          "${GITHUB_WORKSPACE}/kubecf/.github/workflows/pull-request-ci/isolate-network.sh"
          --disable
        continue-on-error: ${{ !matrix.internetless }}
        timeout-minutes: 1

      - name: Rotate Cloud Controller Database
        id: ccdb-rotate
        if: matrix.upgrade != 'upgrade'
        run: |
          source ${GITHUB_WORKSPACE}/catapult/build${CLUSTER_NAME}/.envrc
          testing/ccdb_key_rotation/rotate-ccdb-keys-test.sh

          echo "::group::Wait for KubeCF to be ready again"
          make kubecf-wait
          echo "::endgroup::"
        env:
          CHART: ${{ github.workspace }}/kubecf-bundle/kubecf_release.tgz
        continue-on-error: ${{ !matrix.ccdb-rotate }}
        timeout-minutes: 20

      - name: Post-rotation Smoke Tests
        run: make smoke-tests
        if: steps.ccdb-rotate.outcome == 'success'
        continue-on-error: ${{ !matrix.ccdb-rotate }}
        timeout-minutes: 10

      - name: Upgrade Operator to Same Version
        if: matrix.upgrade == 'upgrade'
        run: make cf-operator-apply
        env:
          CHART: "${{ github.workspace }}/kubecf-bundle/cf-operator.tgz"
        timeout-minutes: 1 # This should take ~10 seconds.

      - name: Wait for Operator to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make cf-operator-wait
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Wait for KubeCF to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-wait
        timeout-minutes: 2 # This should take ~20 seconds.

      - name: Upgrade KubeCF to Same Version
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-apply
        env:
          CHART: ${{ github.workspace }}/kubecf-bundle/kubecf_release.tgz
          FEATURE_EIRINI: ${{ matrix.backend == 'eirini' }}
          VALUES: ${{ github.workspace }}/kubecf-values.yaml
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Wait for KubeCF to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-wait
        timeout-minutes: 30 # This should take ~15 minutes.

      - name: List Releases (Upgrade Operator to Same Version)
        run: helm ls --all-namespaces
        timeout-minutes: 1 # This should take ~20 seconds.

      - name: Run Smoke Tests
        if: matrix.upgrade == 'upgrade'
        run: make smoke-tests
        timeout-minutes: 10

      - name: Upgrade Operator to Future Version
        if: matrix.upgrade == 'upgrade'
        run: make cf-operator-apply
        env:
          CHART: "${{ github.workspace }}/kubecf-bundle-next/cf-operator.tgz"
        timeout-minutes: 1 # This should take ~10 seconds.

      - name: Wait for Operator to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make cf-operator-wait
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Wait for KubeCF to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-wait
        timeout-minutes: 2 # This should take ~20 seconds.

      - name: Upgrade KubeCF to Future Version
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-apply
        env:
          CHART: ${{ github.workspace }}/kubecf-bundle-next/kubecf_release.tgz
          FEATURE_EIRINI: ${{ matrix.backend == 'eirini' }}
          VALUES: ${{ github.workspace }}/kubecf-values.yaml
        timeout-minutes: 1 # This should take ~30 seconds.

      - name: Wait for KubeCF to be Ready
        if: matrix.upgrade == 'upgrade'
        run: make kubecf-wait
        timeout-minutes: 30 # This should take ~15 minutes.

      - name: List Releases (Upgrade to Future Version)
        run: helm ls --all-namespaces
        timeout-minutes: 1 # This should take ~20 seconds.

      - name: Run Smoke Tests
        if: matrix.upgrade == 'upgrade'
        run: make smoke-tests
        timeout-minutes: 10

      # Get resource info for debugging
      - name: Get Resource Info
        if: always()
        run: |
          set +o errexit
          gcloud auth activate-service-account --key-file=${GKE_CRED_JSON}
          resources=(
            BOSHDeployment
            QuarksJob
            QuarksStatefulSet
            Job
            StatefulSet
            Endpoints
            Pods
          )

          printf "::group::Namespaces\n"
          kubectl get namespaces --output=wide
          printf "::endgroup::\n"
          for namespace in cf-operator kubecf ; do
            for resource in "${resources[@]}" ; do
              printf "::group::%s/%s\n" "${namespace}" "${resource}"
              kubectl get "${resource}" --namespace="${namespace}" --output=wide
              printf "::endgroup::\n"
            done
          done
        timeout-minutes: 5

      # Upload kubecf's values.yaml for debugging
      - name: Upload config
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.backend }}-values.yaml
          path: ${{ github.workspace }}/kubecf-values.yaml
        timeout-minutes: 5

      # Fetch logs for debugging
      - name: Fetch logs
        id: fetch-logs
        if: failure()
        run: |
          gcloud auth activate-service-account --key-file=${GKE_CRED_JSON}
          # Running klog.sh twice will grab logs from both namespaces
          dev/kube/klog.sh -f -r cf-operator
          dev/kube/klog.sh -f -r
        timeout-minutes: 60
        continue-on-error: true

      # Upload logs for debugging
      - name: Upload logs
        # Even if the fetch logs step failed, we may have _some_ logs from the
        # operator part; try to upload anyway.
        if: always() && steps.fetch-logs.outcome != 'skipped'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.backend }}-klog.tgz
          path: ${{ github.workspace }}/kubecf/klog.tar.gz
        timeout-minutes: 5
        continue-on-error: true

      # Teardown created k8s cluster
      - name: kubernetes:teardown
        if: always()
        run: make clean
        working-directory: catapult
        env:
          GKE_CLUSTER_NAME: kubecf-ci-${{ github.run_id }}-${{ matrix.backend }}
        timeout-minutes: 20
